FROM node:lts-alpine

ARG DATABASE_URL 
ARG ALGOLIA_API_KEY 
ARG ALGOLIA_APP_ID 
ARG ALGOLIA_INDEX_PREFIX 
ARG EMAIL_PROVIDER_API_KEY 

ENV DATABASE_URL=$DATABASE_URL
ENV ALGOLIA_API_KEY=$ALGOLIA_API_KEY
ENV ALGOLIA_APP_ID=$ALGOLIA_APP_ID
ENV ALGOLIA_INDEX_PREFIX=$ALGOLIA_INDEX_PREFIX
ENV EMAIL_PROVIDER_API_KEY=$EMAIL_PROVIDER_API_KEY

#==============#
# PROVISIONING #
#==============#
WORKDIR /app
COPY package*.json ./

RUN yarn --frozen-lockfile
COPY . /app

CMD yarn start
EXPOSE 8080