version: '3.8'

services:
  db:
    image: 'postgres:13-alpine'
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    container_name: hasura
    ports:
      - '8081:8080'
    depends_on:
      - db
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' 

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - '8082:80'
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    