export type TrackEventPrefix =
  | 'PUSH_NOTIFICATION_FOLLOW_REQUEST'
  | 'PUSH_NOTIFICATION_PROMOTED_TAG'
  | 'PUSH_NOTIFICATION_POST_REPLIED'
  | 'PUSH_NOTIFICATION_FOLLOWEE_POSTED'
  | 'PUSH_NOTIFICATION_SAME_POST_REPLIED'
  | 'PUSH_NOTIFICATION_POST_VANISHING_'
