export type TRACK_EVENT =
  | 'FOLLOW_REQUEST_PUSH_NOTIFICATION_SENT'
  | 'NEW_LIVE_TAG_PUSH_NOTIFICATION_SENT'
  | 'POST_REPLIED_PUSH_NOTIFICATION_SENT'
  | 'FOLLOWEE_POSTED_PUSH_NOTIFICATION_SENT'
  | 'SAME_POST_REPLIED_PUSH_NOTIFICATION_SENT'
  | 'POST_VANISHING_PUSH_NOTIFICATION_SENT'
