export type TrackEventPrefix =
  | 'PUSH_NOTIFICATION_PROMOTED_TAG'
  | 'PUSH_NOTIFICATION_POST_REPLIED'
  | 'PUSH_NOTIFICATION_SAME_POST_REPLIED'
  | 'PUSH_NOTIFICATION_POSTED_ON_YOUR_TAG'
  | 'PUSH_NOTIFICATION_FOLLOWEE_POSTED_ON_TAG'
  | 'PUSH_NOTIFICATION_FOLLOWEE_CREATED_TAG'
