export type TrackEventPrefix =
  | 'PUSH_NOTIFICATION_FOLLOWEE_CREATED_TAG'
  | 'PUSH_NOTIFICATION_IS_NOW_FOLLOWING_YOU'
  | 'PUSH_NOTIFICATION_REACTED_TO_YOUR_POST'
  | 'PUSH_NOTIFICATION_REPLIED_TO_SAME_POST_AS_YOU'
  | 'PUSH_NOTIFICATION_REPLIED_TO_YOUR_POST'
  | 'PUSH_NOTIFICATION_THERE_ARE_NEW_POSTS_ON_YOUR_TAG'
  | 'PUSH_NOTIFICATION_USER_MENTIONED_YOU'
