-- AlterTable
ALTER TABLE "Activity" ADD COLUMN     "date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;
